name: harmony_sdk
version: 0.0.1
homepage: https://github.com/harmony-development/harmony-dart-sdk
environment:
  sdk: '>=2.0.0 <3.0.0'
description: >-
  The SDK for the Harmony protocol.
dependencies:
  http: ^0.12.1
  async: ^2.4.1
  web_socket_channel: ^1.1.0
  json_annotation: ^3.0.0
  json_serializable: ^3.3.0
dev_dependencies:
  build_runner: ^1.0.0
