name: harmony_sdk
version: 0.0.4
homepage: https://github.com/harmony-development/harmony-dart-sdk
environment:
  sdk: '>=2.1.0 <3.0.0'
description: >-
  An idiomatic dart SDK for the Harmony chat protocol, allowing one to
  write clients, bots, and other things speaking it.
dependencies:
  protobuf: ^1.0.1
  grpc: ^2.3.0
  fixnum: ^0.10.11
  async: ^2.4.1
dev_dependencies:
  build_runner: ^1.0.0
